source:
  adapter: postgresql
  database: cupcakesinc_productexpand_source
  username: awadmin
  password: awadmin
  host: localhost
  pool: 5

etl_execution:
  adapter: postgresql
  database: cupcakesinc_etl_execution
  username: awadmin
  password: awadmin
  host: localhost
  pool: 5
  encoding: unicode

development:
  adapter: postgresql
  database: cupcakesinc_productexpand_datawarehouse
  username: awadmin
  password: awadmin
  host: localhost
  pool: 5
  encoding: utf8
  local_infile: true
